version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: inscripciones-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sistema_inscripciones
      MYSQL_USER: inscripciones
      MYSQL_PASSWORD: inscripciones123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./Backend
    container_name: inscripciones-backend
    depends_on:
      - mysql
    environment:
      MYSQL_DSN: inscripciones:inscripciones123@tcp(mysql:3306)/sistema_inscripciones?parseTime=true
    env_file:
      - ./Backend/.env
    ports:
      - "8080:8080"
    restart: always
    command: ["/app/wait-for-mysql.sh", "mysql", "/app/backend"]

  frontend:
    build: ./Frontend
    container_name: inscripciones-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080/api
    ports:
      - "3000:3000"
    restart: always

volumes:
  mysql_data:
